type Query {
  greeting: String
  students: [Student]
  studentById(id: ID!): Student
}

type Student {
  id: ID!
  fullName: String
  major: Major
  college: College
}

enum Major {
  BIOLOGY
  ENGINEERING
  SCIENCE
}

type College {
  name: String
}
